<a href="https://colab.research.google.com/github/DCI-alxogm/ml2023-DavRo24/blob/main/Ago11-12/Notas-Tarea1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introducción a Numpy

---



In [31]:
import numpy as np
x=np.random.seed(0)  #Inicio de datos random

x1 = np.random.randint(10, size=6)  #Matriz de una dimensión
x2 = np.random.randint(10, size=(3, 4))  #Matriz de dos dimensiones
x3 = np.random.randint(10, size=(3, 4, 5))  #Matriz de tres dimensiones
print(x1)
print(x2[2,3]) #Seleccionamos e imprimimos el elemento mencionado por [fila, columna]
print(x1[:2]) #:número hace que podamos leer los datos a partir de la posicón número para atrás
x1[2:]        #número: Hace lo contrario, lee los datos a partir de la posión número, tomando número en la lista
c = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([[93],
             [22]])
np.concatenate([c, y]) #concatenando vectores
g = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([g,g]))#Concatenando matríces
np.concatenate([g,g], axis=1)#Concatenando matríces pero concatena por filas
np.vstack([c,g]) #Concatenando vectores-matrices verticales
np.hstack([z,g]) #Concatenando cadenas horizontales

[5 0 3 3 7 9]
7
[5 0]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


array([[93,  1,  2,  3],
       [22,  4,  5,  6]])

##Distintas operaciones con arrays

In [34]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)
min(big_array), max(big_array)
M = np.random.random((3, 4))
print(M)
M.sum()
M.min(axis=0)
M.max(axis=1)

121 ms ± 35.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
369 µs ± 6.19 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[[0.88459013 0.86339669 0.14849708 0.69583359]
 [0.94857058 0.82859362 0.30826908 0.15673665]
 [0.090362   0.01082926 0.56097913 0.75643017]]


array([0.88459013, 0.94857058, 0.75643017])

##Pandas

In [41]:
import pandas as pd
datos = pd.Series([1.25, 1.5, 1.75, 2.0])
datos.values
datos.index
datos[1:3]
datos = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
datos
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Los Datos manejados por la biblioteca pandas son más fáciles de manipullar así como ya tienen varias funciones agregadas que pueden ser de mucha ayuda, en lugar de manejar todo con las funciones completas de numpy

In [45]:
population['California']
population['California':'Illinois']
pd.Series(datos)
pd.Series([2, 4, 6])
pd.Series(5, index=[100, 200, 300])


100    5
200    5
300    5
dtype: int64

Datos manipulados y convertidos en tablas, hay que leer más la documentación para poder sacar más de estos datos

In [48]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area
states = pd.DataFrame({'population': population, #Data.frame nos ayuda a hacer tablas chidas
                       'area': area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995